### ISSUE TITLE
question about 'randomly crop the local images from the uncertain regions'

### ISSUE THREAD

**Issue by Jingfeng-Tang** [rulixiang/ToCo#11]
Hello! Thanks for you brilliant work in WSSS. 
in camutils.py
in function of ’def crop_from_roi_neg(images, roi_mask=None, crop_num=8, crop_size=96):’
`
roi_index = (roi_mask[i1, margin:(h-margin), margin:(w-margin)] <= 1).nonzero()  # 48:400, 48:400
`
Based on the code, we search for negative sample coordinates within the range of 48 to 400，If randomly selected (399，399)

`
h0, w0 = crop_index[i2, 0], crop_index[i2, 1]  # centered at (h0, w0)
temp_crops[i1, i2, ...] = images[i1, :, h0:(h0+crop_size), w0:(w0+crop_size)]
`
h0 = 399， w0 = 399 and crop_size = 96 , h0+cropsize = 495 
495 will go out of range(0, 448)

**Comment by rulixiang** [comment]
Hey, thanks for your interest.
I'm afraid your computation on `roi_index` is wrong. Here's a toy test.
```python
crop_size = 96
h = w = 448
margin = crop_size // 2
roi_mask = torch.rand((2,h,w))
roi_index = (roi_mask[0, margin:(h-margin), margin:(w-margin)]).nonzero()
print(roi_index)

''' This snippet will give:
tensor([[  0,   0],
        [  0,   1],
        [  0,   2],
        ...,
        [351, 349],
        [351, 350],
        [351, 351]])
'''
```

**Comment by Jingfeng-Tang** [comment]
thanks！
