### ISSUE TITLE
使用vit_base_patch16_224backbone

### ISSUE THREAD

**Issue by pipizhum** [rulixiang/ToCo#14]
为什么使用vit_base_patch16_224精度很低？怎么使用vit_base_patch16_224预训练权重？

**Comment by rulixiang** [comment]
你好，你未提供具体信息，我无法判断原因。
使用vit_base_patch16_224只需将backbone参数改成vit_base_patch16_224。

**Comment by hly1999** [comment]
Hellow, I have the same question, I change backbone to vit_base_patch16_224, but the result is always low than report , how to deal with it?

**Comment by zwyang6** [comment]
> https://github.com/rulixiang/ToCo/blob/e13514d9a89a6c0b4131392a465fcf368a562b4e/model/backbone/vit.py#L237

Hello, Thanks for your contributions! I am wondering why the gradient of the position embedding in the provided vit is off ? shoudln't it be optimized? `

**Comment by ZhaofengSHI** [comment]
我遇到了一样的问题，发现是因为由于timm版本原因，vit预训练权重没有自动下载导致没有成功载入，把timm版本换成0.5.4就好了
