### ISSUE TITLE
Reproducing Results

### ISSUE THREAD

**Issue by AmeenAli** [rulixiang/ToCo#2]
Hello!

Thanks for sharing this amazing work! I have a few questions regarding the steps of reproducing the results : 

The numbers are written in the Table inside the README.md file does not match the results in the log attached, It's written that "Note that the final performance is post-processed with multi-scale test and CRF, while the performance in log isn't." , so my question, does the current code provides this? if not, can you refer me to the code you have used to do that?

Thanks!

**Comment by rulixiang** [comment]
Thanks for your interest. The post-processing code is available [here](https://github.com/rulixiang/ToCo/blob/main/tools/infer_seg_voc.py).

I'll try to update the table in README to avoid misunderstanding.
