### ISSUE TITLE
Evaluation of pseudo labels

### ISSUE THREAD

**Issue by AmeenAli** [rulixiang/ToCo#4]
Hi!

Where can I find the code parts for the Evaluation of pseudo labels?

Thanks!

**Comment by rulixiang** [comment]
Hey, the evaluation of pseudo labels can be found [here](https://github.com/rulixiang/ToCo/blob/main/tools/infer_cam.py) or [here](https://github.com/rulixiang/ToCo/blob/ab46ceb3c8ce63f1d532c8aec0d9126507ed2441/scripts/dist_train_voc_seg_neg.py#L89).

**Comment by liaochuanlin** [comment]
Is a file bilateralfilter_batch missing?
