### ISSUE TITLE
cls_labels_onehot.npy

### ISSUE THREAD

**Issue by pqu2** [rulixiang/ToCo#5]
Thank you for sharing!
Could you please show me how to generate the file cls_labels_onehot.npy  ?

**Comment by rulixiang** [comment]
Hey, `cls_labels_onehot.npy` contains the image-level labels of images in the training set. You can understand it from the code [here](https://github.com/rulixiang/ToCo/blob/ab46ceb3c8ce63f1d532c8aec0d9126507ed2441/datasets/voc.py#L22).
