### ISSUE TITLE
img_box in cam_to_label function.

### ISSUE THREAD

**Issue by King-king424** [rulixiang/ToCo#7]
![image](https://user-images.githubusercontent.com/39642013/225933915-0886bea5-dac3-4dda-8853-845cc7d27f4e.png)
Thank you for sharing your wonderful work. I have some questions about the specific implementation. The img_box here does not seem to be mentioned in the paper. I would like to know how img_box came about? What is its specific function? What is the effect of not using img_box in the cam_to_label function? Looking forward to your answer.

**Comment by rulixiang** [comment]
Hey, in each iteration, we need to pad images of different sizes and random crop images from the padded images. The `img_box` denotes the real image region in a cropped image. See [here](https://github.com/rulixiang/ToCo/blob/ab46ceb3c8ce63f1d532c8aec0d9126507ed2441/datasets/transforms.py#L147) for details.
 
The pixels out of the `img_box` are labelled as ignored, which is shown in the red box in your figure. I didn't test the results without `img_box`, but I believe it should not influence the final result much.
