### ISSUE TITLE
No module named 'bilateralfilter' 

### ISSUE THREAD

**Issue by massica17** [rulixiang/ToCo#9]
I try pip install bilateralfilter and sucess, but still still reporting this error

**Comment by whnwwwhhhnnn** [comment]
Excuse me, how is this problem solved?

**Comment by rulixiang** [comment]
Hey, to use `reg loss`,  see https://github.com/rulixiang/ToCo#build-reg-loss.

**Comment by massica17** [comment]
ok，thanks，really help
